baseURL = 'https://cheeseepedia.org/'
languageCode = 'en-us'
title = 'Cheese-E-Pedia'
theme = 'sixtyth-fortran'
refLinksErrorLevel = 'WARNING'
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'All Pages'
pageRef = '/wiki'
weight = 40

[taxonomies]
  category = 'categories'
  tag = 'tags'

[params]
  dateFormat = "2006-1-2"

ignoreFiles = "/static/Code/.*"