backend:
  name: github
  repo: The64thGamer/cheeseepedia
  branch: main
  use_graphql: false
  open_authoring: true
  base_url: https://sveltia-cms-auth.a22j2udvt.workers.dev

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

media_folder: "static/photos" # Media files will be stored in the repo under static/images/uploads
public_folder: "/photos" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://cheeseepedia.org
display_url: https://cheeseepedia.org
publish_mode: editorial_workflow

collections:
  - name: "wiki"
    label: "Articles"
    folder: "content/wiki/"
    preview_path: "wiki/{{filename}}"
    create: true
    extension: html
    format: toml-frontmatter
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }
      - { label: "(Keep This False)", name: "draft", widget: "boolean", default: false, required: true}
      - { label: "Start Date (Formatted 2024-12-31)", name: "startDate", widget: "string", required: false}
      - { label: "End Date (Leave blank if not ended, set to 0000-00-00 if Unknown)", name: "endDate", widget: "string", required: false}
      - { label: "Thumbnail (example.avif)", name: "pageThumbnailFile", widget: "string", required: false}
      - label: "Contributors (List your Username here!)"
        name: "contributors"
        widget: "list"
        required: true
        min: 1
        max: 1000
        field: {label: Username, name: username, widget: string}
      - label: "Citations (List sources here!)"
        name: "citations"
        widget: "list"
        required: true
        min: 1
        max: 1000
        field: {label: Source, name: source, widget: string}
      - label: "Credits"
        name: "credits"
        widget: "list"
        required: false
        field: {label: Credit, name: credit, widget: string}
      - { label: "Manufacturer", name: "manufacturer", widget: "string", required: false}
      - { label: "Units Produced", name: "unitsProduced", widget: "string", required: false}
      - { label: "Wholesale Price", name: "wholesalePrice", widget: "string", required: false}
      - { label: "Dimensions", name: "dimensions", widget: "string", required: false}
      - label: "Download Links (example.org|Description)"
        name: "downloadLinks"
        widget: "list"
        required: false
        field: {label: Link | Desc, name: link, widget: string}
      - label: "Prices (Price|Date) ($4.99|1983-12-31)"
        name: "prices"
        widget: "list"
        required: false
        field: {label: Price | Desc, name: price, widget: string}
      - label: "Latitude, Longitude"
        name: "latitudeLongitude"
        min: 0
        max: 2
        widget: "list"
        required: false
        field: {label: LatLong, name: latlong, widget: string}
      - label: "Tags"
        name: "tags"
        widget: "select"
        min: 1
        max: 5
        multiple: true
        required: true
        options:
          - { label: "Animatronic Shows", value: "Animatronic Shows" }
          - { label: "Stage Variations", value: "Stage Variations" }
          - { label: "Animatronics", value: "Animatronics" }
          - { label: "Retrofits", value: "Retrofits" }
          - { label: "Costumed Characters", value: "Costumed Characters" }
          - { label: "Animatronic Repair & Preservation", value: "Animatronic Repair & Preservation" }
          - { label: "Showtapes", value: "Showtapes" }
          - { label: "Showtape Formats", value: "Showtape Formats" }
          - { label: "Live Shows", value: "Live Shows" }
          - { label: "Showtape Puppets", value: "Showtape Puppets" }
          - { label: "Family Vision", value: "Family Vision" }
          - { label: "ShowBiz Pizza Programs", value: "ShowBiz Pizza Programs" }
          - { label: "Merchandise", value: "Merchandise" }
          - { label: "Menu Items", value: "Menu Items" }
          - { label: "Tokens", value: "Tokens" }
          - { label: "Tickets", value: "Tickets" }
          - { label: "Movies", value: "Movies" }
          - { label: "Video Games", value: "Video Games" }
          - { label: "Locations", value: "Locations" }
          - { label: "Arcade Games", value: "Arcade Games" }
          - { label: "Employee Wear", value: "Employee Wear" }
          - { label: "Remodels & Initiatives", value: "Remodels & Initiatives" }
          - { label: "Store Fixtures", value: "Store Fixtures" }
          - { label: "Ad Vehicles", value: "Ad Vehicles" }
          - { label: "Animatronic Control Systems", value: "Animatronic Control Systems" }
          - { label: "Other Systems", value: "Other Systems" }
          - { label: "Programming Systems", value: "Programming Systems" }
          - { label: "Promotional Material", value: "Promotional Material" }
          - { label: "Documents", value: "Documents" }
          - { label: "Corporate Documents", value: "Corporate Documents" }
          - { label: "Training, Updates, & Company Media", value: "Training, Updates, & Company Media" }
          - { label: "News Footage", value: "News Footage" }
          - { label: "Commercials", value: "Commercials" }
          - { label: "History", value: "History" }
          - { label: "Events", value: "Events" }
          - { label: "Characters", value: "Characters" }
      - label: "Categories"
        name: "categories"
        widget: "select"
        min: 1
        max: 5
        multiple: true
        required: true
        options:
        - { label: "Celebration Station", value: "Celebration Station" }
        - { label: "Chuck E. Cheese's", value: "Chuck E. Cheese's" }
        - { label: "Disney Parks", value: "Disney Parks" }
        - { label: "Jungle Jim's", value: "Jungle Jim's" }
        - { label: "Pasquallys Pizza & Wings", value: "Pasquallys Pizza & Wings" }
        - { label: "Pizza Time Theatre", value: "Pizza Time Theatre" }
        - { label: "ShowBiz Pizza Place", value: "ShowBiz Pizza Place" }
        - { label: "Advanced Animations", value: "Advanced Animations" }
        - { label: "Avg Technologies", value: "Avg Technologies" }
        - { label: "Creative Engineering", value: "Creative Engineering" }
        - { label: "Creative Presentations", value: "Creative Presentations" }
        - { label: "Disney Parks", value: "Disney Parks" }
        - { label: "Fantasy Forest", value: "Fantasy Forest" }
        - { label: "Golding Leisure", value: "Golding Leisure" }
        - { label: "Heimotion", value: "Heimotion" }
        - { label: "Hofmann Figuren", value: "Hofmann Figuren" }
        - { label: "Jim Henson's Creature Shop", value: "Jim Henson's Creature Shop" }
        - { label: "Sally Corporation", value: "Sally Corporation" }
        - { label: "Unknown Manufacturers", value: "Unknown Manufacturers" }
        - { label: "Villalobos Producciones", value: "Villalobos Producciones" }
        - { label: "Vp Animations", value: "Vp Animations" }
        - { label: "Chuck E. Cheese in the Galaxy 5000", value: "Chuck E. Cheese in the Galaxy 5000" }
        - { label: "Five Nights at Freddy's", value: "Five Nights at Freddy's" }
        - { label: "Five Nights at Freddy's 2", value: "Five Nights at Freddy's 2" }
        - { label: "The Rock-afire Explosion Documentary", value: "The Rock-afire Explosion Documentary" }

  - name: "transcriptions" # Used in routes, e.g., /admin/collections/blog
    label: "Transcriptions" # Used in the UI
    folder: "content/transcriptions/" # The path to the folder where the documents are stored
    create: true
    slug: "{{slug}}"
    preview_path: "transcriptions/{{filename}}/"
    extension: html
    format: toml-frontmatter
    editor:
      preview: true
    fields: # The field for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "users" # Used in routes, e.g., /admin/collections/blog
    label: "Users" # Used in the UI
    folder: "content/users/" # The path to the folder where the documents are stored
    create: true
    slug: "{{slug}}"
    preview_path: "users/{{filename}}"
    extension: html
    format: toml-frontmatter
    editor:
      preview: true
    fields: # The field for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "meta" # Used in routes, e.g., /admin/collections/blog
    label: "Meta Page" # Used in the UI
    folder: "content/meta/" # The path to the folder where the documents are stored
    create: true
    slug: "{{slug}}"
    preview_path: "meta/{{filename}}"
    extension: html
    format: toml-frontmatter
    editor:
      preview: true
    fields: # The field for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "photos" # Used in routes, e.g., /admin/collections/blog
    label: "Photo" # Used in the UI
    folder: "content/photos/" # The path to the folder where the documents are stored
    create: true
    slug: "{{slug}}"
    preview_path: "photos/{{filename}}"
    extension: html
    format: toml-frontmatter
    editor:
      preview: true
    fields: # The field for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "(Keep This False)", name: "draft", widget: "boolean", default: false, required: true}
      - { label: "Date (Formatted 2024-12-31)", name: "date", widget: "string", required: false}
      - label: "Citations (List sources here!)"
        name: "citations"
        widget: "list"
        min: 1
        max: 1000
        field: {label: Source, name: source, widget: string}
      - label: "Pages Photo Depicts (Use Page Title)"
        name: "pages"
        widget: "list"
        required: true
        min: 1
        max: 1000
        field: {label: Page, name: page, widget: string}
      - label: "Tags"
        name: "tags"
        widget: "select"
        min: 1
        max: 1
        required: true
        options:
          - { label: "Photos", value: "Photos" }
      - label: "Categories"
        name: "categories"
        widget: "select"
        min: 1
        max: 5
        multiple: true
        required: true
        options:
        - { label: "Celebration Station", value: "Celebration Station" }
        - { label: "Chuck E. Cheese's", value: "Chuck E. Cheese's" }
        - { label: "Disney Parks", value: "Disney Parks" }
        - { label: "Jungle Jim's", value: "Jungle Jim's" }
        - { label: "Pasquallys Pizza & Wings", value: "Pasquallys Pizza & Wings" }
        - { label: "Pizza Time Theatre", value: "Pizza Time Theatre" }
        - { label: "ShowBiz Pizza Place", value: "ShowBiz Pizza Place" }
        - { label: "Advanced Animations", value: "Advanced Animations" }
        - { label: "Avg Technologies", value: "Avg Technologies" }
        - { label: "Creative Engineering", value: "Creative Engineering" }
        - { label: "Creative Presentations", value: "Creative Presentations" }
        - { label: "Disney Parks", value: "Disney Parks" }
        - { label: "Fantasy Forest", value: "Fantasy Forest" }
        - { label: "Golding Leisure", value: "Golding Leisure" }
        - { label: "Heimotion", value: "Heimotion" }
        - { label: "Hofmann Figuren", value: "Hofmann Figuren" }
        - { label: "Jim Henson's Creature Shop", value: "Jim Henson's Creature Shop" }
        - { label: "Sally Corporation", value: "Sally Corporation" }
        - { label: "Unknown Manufacturers", value: "Unknown Manufacturers" }
        - { label: "Villalobos Producciones", value: "Villalobos Producciones" }
        - { label: "Vp Animations", value: "Vp Animations" }
        - { label: "Chuck E. Cheese in the Galaxy 5000", value: "Chuck E. Cheese in the Galaxy 5000" }
        - { label: "Five Nights at Freddy's", value: "Five Nights at Freddy's" }
        - { label: "Five Nights at Freddy's 2", value: "Five Nights at Freddy's 2" }
        - { label: "The Rock-afire Explosion Documentary", value: "The Rock-afire Explosion Documentary" }

  - name: "videos" # Used in routes, e.g., /admin/collections/blog
    label: "Video" # Used in the UI
    folder: "content/videos/" # The path to the folder where the documents are stored
    create: true
    slug: "{{slug}}"
    preview_path: "videos/{{filename}}"
    extension: html
    format: toml-frontmatter
    editor:
      preview: true
    fields: # The field for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "admin" # Used in routes, e.g., /admin/collections/blog
    label: "Decap CMS" # Used in the UI
    folder: "static/admin/" # The path to the folder where the documents are stored
    create: true
    slug: "{{slug}}"
    preview_path: "admin/{{filename}}"
    extension: yml
    format: yml
    editor:
      preview: true
    fields: # The field for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }